import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";

// Colors pulled from the Sruwan Inventory logo
const NAVY = [21, 58, 111];
const ORANGE = [245, 130, 31];

/* Loads the logo image and converts it into a base64 data URL,
   since jsPDF needs the raw image data, not just a file path. */
const loadLogoAsDataUrl = () => {
  return new Promise((resolve, reject) => {
    const image = new Image();

    image.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = image.width;
      canvas.height = image.height;

      const context = canvas.getContext("2d");
      context.drawImage(image, 0, 0);

      resolve(canvas.toDataURL("image/png"));
    };

    image.onerror = reject;
    image.src = logo;
  });
};

/* Draws the shared header (logo, company name, report title,
   generated-by, date) at the top of the page. Returns the y position
   where the table should start, so the table never overlaps the header. */
const drawHeader = async (doc, { reportTitle, generatedBy, subtitle }) => {
  const logoDataUrl = await loadLogoAsDataUrl();

  doc.addImage(logoDataUrl, "PNG", 40, 30, 40, 40);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...NAVY);
  doc.text("Sruwan Inventory", 90, 45);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Inventory Management System", 90, 60);

  // Orange accent line under the header
  doc.setDrawColor(...ORANGE);
  doc.setLineWidth(2);
  doc.line(40, 80, 555, 80);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text(reportTitle, 40, 105);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, 40, 120);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by: ${generatedBy}`, 400, 105);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 400, 118);

  return subtitle ? 140 : 130;
};

/* Low Stock Report PDF */
export const generateLowStockPDF = async ({ products, generatedBy }) => {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const startY = await drawHeader(doc, {
    reportTitle: "Low Stock Report",
    generatedBy,
  });

  const rows = products.map((product) => [
    product.key,
    product.name,
    product.category?.name || "Uncategorized",
    String(product.totalQty),
    String(product.lowStockThreshold),
  ]);

  autoTable(doc, {
    startY,
    head: [["Key", "Name", "Category", "Qty", "Threshold"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255 },
    styles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  doc.save(`low-stock-report-${Date.now()}.pdf`);
};

/* Stock Movement Report PDF */
export const generateStockMovementPDF = async ({
  movements,
  generatedBy,
  filterSummary,
}) => {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const startY = await drawHeader(doc, {
    reportTitle: "Stock Movement Report",
    generatedBy,
    subtitle: filterSummary,
  });

  const rows = movements.map((movement) => [
    new Date(movement.createdAt).toLocaleDateString(),
    `${movement.product?.name || ""} (${movement.product?.key || ""})`,
    movement.type,
    `${movement.previousQty} -> ${movement.newQty}`,
    movement.reason || "-",
    movement.createdBy
      ? `${movement.createdBy.firstName} ${movement.createdBy.lastName}`
      : "-",
  ]);

  autoTable(doc, {
    startY,
    head: [["Date", "Product", "Type", "Change", "Reason", "By"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255 },
    styles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  doc.save(`stock-movement-report-${Date.now()}.pdf`);
};